/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  api: [{dirName: 'api', type: 'autogenerated'}],
  docs: [
    'intro',
    require('./sidebars/gettingStartedSidebar.js'),
    require('./sidebars/conceptsSidebar.js'),
    require('./sidebars/packagesSidebar.js'),
    require('./sidebars/reactSidebar.js'),
    require('./sidebars/collaborationSidebar.js'),
    'faq',
  ],
};

module.exports = sidebars;
