/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';

const packagesSidebar = process.env.FB_INTERNAL
  ? {
      href: 'https://lexical.dev/docs/packages/lexical',
      label: 'Packages',
      type: 'link',
    }
  : [
      {
        items: [{dirName: 'packages', type: 'autogenerated'}],
        label: 'Packages',
        type: 'category',
      },
    ];

module.exports = packagesSidebar;
